### ISSUE TITLE
Permission controller keeps stopping

### ISSUE THREAD

**Issue by Rzqnoga** [SuperiorOS/android-issue#1]
## Build date
 
```
SuperiorOS-Thirteen-lancelot-GAPPS-RELEASE-20230211-0602
```

## Expected Behavior

```
It shouldn't appear
```

## Current Behavior

```
It appeared :)
```

## Possible Solution

```
Edit here
```

## Logs link 

```
https://batbin.me/teutonically (error log)
https://ibb.co/2FL5Qtd (screenshot)
```

## Steps to Reproduce

```
1.it happened when I boot superior os for the first time and keeps popping up when using the phone
```

**Comment by Darkstar085** [comment]
@01soni247 clean flash recommended for this build..??

**Comment by Rzqnoga** [comment]
> @01soni247 clean flash recommended for this build..??

I tried dirty flash method but it didn't work it said system is corrupted so I did factory reset then it booted normally

**Comment by Darkstar085** [comment]
> > @01soni247 clean flash recommended for this build..??
> 
> I tried dirty flash method but it didn't work it said system is corrupted so I did factory reset then it booted normally

Can u dm me t.me/Darkstar085 for test build

**Comment by 01soni247** [comment]
Thank you for the report, I'm trying to fix it, sorry for the inconvenience

**Comment by Rzqnoga** [comment]
> Thank you for the report, I'm trying to fix it, sorry for the inconvenience

I was ready for the bugs when i tried new costum rom... It's not a big deal.
I'm happy with this costum rom and i really appreciate your hard work just keep going 🙏

**Comment by 01soni247** [comment]
> > Thank you for the report, I'm trying to fix it, sorry for the inconvenience
> 
> I was ready for the bugs when i tried new costum rom... It's not a big deal. I'm happy with this costum rom and i really appreciate your hard work just keep going 🙏

can you pm me on telegram?

**Comment by Rzqnoga** [comment]
> > > Thank you for the report, I'm trying to fix it, sorry for the inconvenience
> > 
> > 
> > I was ready for the bugs when i tried new costum rom... It's not a big deal. I'm happy with this costum rom and i really appreciate your hard work just keep going 🙏
> 
> can you pm me on telegram?

Yea

**Comment by Rzqnoga** [comment]
> > > Thank you for the report, I'm trying to fix it, sorry for the inconvenience
> > 
> > 
> > I was ready for the bugs when i tried new costum rom... It's not a big deal. I'm happy with this costum rom and i really appreciate your hard work just keep going 🙏
> 
> can you pm me on telegram?

I can't find send me link

**Comment by Darkstar085** [comment]
Fixed here - https://github.com/SuperiorOS/android_frameworks_base/commit/57b9000f31946e98df7ef87a23bae088a11ac235
