### ISSUE TITLE
Redmi Note 9

### ISSUE THREAD

**Issue by M0K3e** [SuperiorOS/android-issue#12]
VoLTE does not work on my Redmi Note 9 phone, I hope that in the next update they will fix that error please.
I have the last update of the month of April.

**Comment by Darkstar085** [comment]
@01soni247 look into it

**Comment by M0K3e** [comment]
If there will be VoLTE solution in the next update? It is that I realized that it is not the only model that has this error, I would greatly appreciate your help please

**Comment by Darkstar085** [comment]
> If there will be VoLTE solution in the next update? It is that I realized that it is not the only model that has this error, I would greatly appreciate your help please

This isn't ROM side issue, this is device specific so wait for maintainer to fix..

**Comment by 01soni247** [comment]
> Apakah akan ada solusi VoLTE di update berikutnya? Saya menyadari bahwa ini bukan satu-satunya model yang memiliki kesalahan ini, saya sangat menghargai bantuan Anda

this happened after Upadet?

**Comment by 01soni247** [comment]
> If there will be VoLTE solution in the next update? It is that I realized that it is not the only model that has this error, I would greatly appreciate your help please

I forgot something, I will fix it in a few days

**Comment by M0K3e** [comment]
> > Apakah akan ada solusi VoLTE di update berikutnya? Saya menyadari bahwa ini bukan satu-satunya modelo yang memiliki kesalahan ini, saya sangat menghargai bantuan Anda
> 
> esto sucedió después de Upadet?

That's right, the error with VoLTE happened after having updated to the latest version in April

**Comment by M0K3e** [comment]
> > ¿Habrá una solución VoLTE en la próxima actualización? Es que me di cuenta que no es el único modelo que tiene este error, agradecería mucho su ayuda por favor
> 
> Olvidé algo, lo arreglaré en unos días.

I thank you for giving me a positive answer, but does that mean that there will be another update in these days to fix this VoLTE error, or will the error be fixed until the next update in May?

**Comment by 01soni247** [comment]
> > > ¿Habrá una solución VoLTE en la próxima actualización? Es que me di cuenta que no es el único modelo que tiene este error, agradecería mucho su ayuda por favor
> > 
> > 
> > Olvidé algo, lo arreglaré en unos días.
> 
> I thank you for giving me a positive answer, but does that mean that there will be another update in these days to fix this VoLTE error, or will the error be fixed until the next update in May?

Fix in 2-5 day

**Comment by M0K3e** [comment]
> > > > ¿Habrá una solución VoLTE en la próxima actualización? Es que me di cuenta que no es el único modelo que tiene este error, agradecería mucho su ayuda por favor
> > > 
> > > 
> > > Olvidé algo, lo arreglaré en unos días.
> > 
> > 
> > I thank you for giving me a positive answer, but does that mean that there will be another update in these days to fix this VoLTE error, or will the error be fixed until the next update in May?
> 
> Fix in 2-5 day

There is still no update fixing the VoLTE bug, right sir?

**Comment by 01soni247** [comment]
> > > > > ¿Habrá una solución VoLTE en la próxima actualización? Es que me di cuenta que no es el único modelo que tiene este error, agradecería mucho su ayuda por favor
> > > > 
> > > > 
> > > > Olvidé algo, lo arreglaré en unos días.
> > > 
> > > 
> > > I thank you for giving me a positive answer, but does that mean that there will be another update in these days to fix this VoLTE error, or will the error be fixed until the next update in May?
> > 
> > 
> > Fix in 2-5 day
> 
> There is still no update fixing the VoLTE bug, right sir?

Waiting 2-3 days pliss

**Comment by M0K3e** [comment]
> > > > > > ¿Habrá una solución VoLTE en la próxima actualización? Es que me di cuenta que no es el único modelo que tiene este error, agradecería mucho su ayuda por favor
> > > > > 
> > > > > 
> > > > > Olvidé algo, lo arreglaré en unos días.
> > > > 
> > > > 
> > > > I thank you for giving me a positive answer, but does that mean that there will be another update in these days to fix this VoLTE error, or will the error be fixed until the next update in May?
> > > 
> > > 
> > > Fix in 2-5 day
> > 
> > 
> > There is still no update fixing the VoLTE bug, right sir?
> 
> Waiting 2-3 days pliss

The wait is very frustrating for me, SuperiorOS is one of the best Custom's ROMs out there, I'll try to meditate so I don't go crazy waiting for the update

**Comment by M0K3e** [comment]
> > > > > > ¿Habrá una solución VoLTE en la próxima actualización? Es que me di cuenta que no es el único modelo que tiene este error, agradecería mucho su ayuda por favor
> > > > > 
> > > > > 
> > > > > Olvidé algo, lo arreglaré en unos días.
> > > > 
> > > > 
> > > > I thank you for giving me a positive answer, but does that mean that there will be another update in these days to fix this VoLTE error, or will the error be fixed until the next update in May?
> > > 
> > > 
> > > Fix in 2-5 day
> > 
> > 
> > There is still no update fixing the VoLTE bug, right sir?
> 
> Waiting 2-3 days pliss

Sir, tomorrow Friday, the SuperiorOS update will be available, correcting the error with VoLTE?

**Comment by 01soni247** [comment]
> > > > > > > ¿Habrá una solución VoLTE en la próxima actualización? Es que me di cuenta que no es el único modelo que tiene este error, agradecería mucho su ayuda por favor
> > > > > > 
> > > > > > 
> > > > > > Olvidé algo, lo arreglaré en unos días.
> > > > > 
> > > > > 
> > > > > I thank you for giving me a positive answer, but does that mean that there will be another update in these days to fix this VoLTE error, or will the error be fixed until the next update in May?
> > > > 
> > > > 
> > > > Fix in 2-5 day
> > > 
> > > 
> > > There is still no update fixing the VoLTE bug, right sir?
> > 
> > 
> > Waiting 2-3 days pliss
> 
> Sir, tomorrow Friday, the SuperiorOS update will be available, correcting the error with VoLTE?
Next Month

**Comment by Darkstar085** [comment]
Fixed here - https://t.me/superior_os/1958
