### ISSUE TITLE
Can't change volume with external wired headphones buttons

### ISSUE THREAD

**Issue by autodistries** [SuperiorOS/android-issue#17]
I don't know if this is the right place, or if my issue is device-specific, but everything is in the title : clicking the wired headphone's volume buttons does not change the volume. Instead it seems to select something on the screen (like an external keyboard would maybe do by pressing some accessibility key).
(Note that a bluetooth headet's buttons work)

Device: Spesn (Redmi Note 11) with 9 May update (aka latest)

**Comment by SHADOW-REX** [comment]
Please abide by proper issue format!

**Comment by autodistries** [comment]
This is probably device-specific as no other rom i've tried has support for this
