### ISSUE TITLE
WiFi not turning on

### ISSUE THREAD

**Issue by andimattes** [SuperiorOS/android-issue#2]
## Build date

```
SuperiorOS-Thirteen-avicii-GAPPS-RELEASE-20230218-1017
```

## Expected Behavior

```
Wifi turns on and should start scanning for access points
```

## Current Behavior

```
Seems like wifi turns on but does not scan for APs
```

## Possible Solution

```
Nothing for now
```

## Logs link 

```
https://batbin.me/transversally (log)
https://ibb.co/njtPk14 (Screenshot)
```

## Steps to Reproduce
```
1. Pull down notification area
2. Click on Wifi tile
3. Click on slider to turn on Wifi
4. Wait for APs to be found
```

**Comment by Darkstar085** [comment]
Tell flashing method..

**Comment by andimattes** [comment]
Adb sideload in recovery

**Comment by Darkstar085** [comment]
> Adb sideload in recovery

Did you flashed from oos 12..??

**Comment by Darkstar085** [comment]
Clean flash from oos 12 will fix the issue

**Comment by andimattes** [comment]
I was on January update and then clean flashed feb update. What should I do different?

**Comment by Darkstar085** [comment]
@andimattes Flash oos 12 then flash the rom.. u didn't read the chabgelogs..??

**Comment by andimattes** [comment]
Ah just saw it, my fault...
Do you have a link to a guide on how to flash OOS12?

**Comment by Darkstar085** [comment]
> Ah just saw it, my fault... Do you have a link to a guide on how to flash OOS12?

Join here - https://t.me/recovery_avicii
