### ISSUE TITLE
Not giving signature spoof permissions

### ISSUE THREAD

**Issue by lucastheguyy** [SuperiorOS/android-issue#20]
## Build date

```
Latest one as of may 17 for merlinx
```

## Expected Behavior

```
It should give the permission
```

## Current Behavior

```
It refuses to give permissions
```

## Possible Solution

```
```

## Logs link 

```
Don't know how to export logs
```

## Steps to Reproduce

```
1.try to give signature spoof permissions to an app

```

https://github.com/SuperiorOS/android-issue/assets/76494070/9b9a8aa3-fc42-4aa1-9330-15a233031d56

**Comment by Darkstar085** [comment]
EOL.. no further support..
