### ISSUE TITLE
Please add radiofm app features And please change the screen brightness in the framework on Redmi 9 LANCELOT 

### ISSUE THREAD

**Issue by ahmad-official** [SuperiorOS/android-issue#21]
Please add the FMradio application, because this feature is already available on Redmi 9, but has not yet been built on the device

And please change it to lower the screen brightness in the framework on Redmi 9 LANCELOT

**Comment by 01soni247** [comment]
my enlightenment follows the official lineage os , Radio fm i will mind to add it in the future
