### ISSUE TITLE
In display fingerprint doesn't work after reboot. 

### ISSUE THREAD

**Issue by ij-israfil** [SuperiorOS/android-issue#23]
After add fingerprint its working fine but if I reboot the device and tried to unlock with fingerprint it doesn't work. I need remove and added again to work fingerprint. 

https://github.com/SuperiorOS/android-issue/assets/86546896/e2c7c1d9-6fd4-42e4-b8a3-72bbe2af3081

**Comment by Darkstar085** [comment]
No proper format
