### ISSUE TITLE
Permissions manager can't load permission

### ISSUE THREAD

**Issue by cornelgd** [SuperiorOS/android-issue#24]
## Build date

```
 SuperiorOS-Thirteen- fajita 
TQ3A.230705.001
```

## Expected Behavior

```
When going into privacy/permissions manager it should display the permissions for all apps, grouped by category. Instead, it shows loading for all categories
```

## Current Behavior

```
it shows loading
```

## Possible Solution

```
Edit here
```

## Logs link 

```
https://batbin.me/cc7dbc66c15d4ab3b37a19f149674431
```

## Steps to Reproduce

```
1.go to aettings/privacy/permissions manager
2.
3.
4.
```

**Comment by dominator-prime** [comment]
It's working fine 
Check your side issue what you modefied  or flashed 
If you flashed nothing do clean flash 

![IMG_20230917_091101_102](https://github.com/SuperiorOS/android-issue/assets/18100664/923ab968-dbd0-4f07-9cb5-650145ff7beb)
