### ISSUE TITLE
Status bar clock issue

### ISSUE THREAD

**Issue by R9TRH** [SuperiorOS/android-issue#25]
## Build date

```
Thirteen | EXTENDED | Vanilla - Sep 19 20:48:11 IST - Poco X5 Pro 5G (redwood)
```

## Expected Behavior

```
Clock color should dynamicly change between white/dark in various status bar colors, not static color. At least there should be toggle 
```

## Current Behavior

```
The color is static, it needs a background chip to be always readable.
```

## Possible Solution

```
Add a toggle for dynamic color
```

## Logs link 

```
No log needed
```

## Steps to Reproduce

```
1. Set clock color to black and disable bg chip
2. Go to a black app that makes status bar dark
3. Now you can't see the clock
4. I'm sure it's source issue, that's why I'm reporting on EXTENDED version.
```

**Comment by Darkstar085** [comment]
Are you sure You are using **SuperiorOS**

**Comment by R9TRH** [comment]
> Are you sure You are using **SuperiorOS**

Bro 😐 Superior Extended vanilla.

**Comment by Darkstar085** [comment]
@R9TRH Thats not SuperiorOS

**Comment by R9TRH** [comment]
> @R9TRH Thats not SuperiorOS

![Screenshot_20230920-125025](https://github.com/SuperiorOS/android-issue/assets/106015729/a00ab987-61dd-456a-8c13-65d24d714700)

**Comment by Darkstar085** [comment]
Thats not our source..

**Comment by R9TRH** [comment]
> Thats not our source..

Oh okay 👍
Thanks for reply
