### ISSUE TITLE
Problems with miatoll Android 14 latest update 

### ISSUE THREAD

**Issue by Sayak46** [SuperiorOS/android-issue#26]
Bulid- SuperiorOS-Fourteen-miatoll-GAPPS-RELEASE-20240102-0221.zip

> **In Settings** -

**Superior Lab**- There is nothing showing under lockscreen, buttons and notification option.
![Screenshot_20240105-003113_Settings](https://github.com/SuperiorOS/android-issue/assets/155672212/4c7e2ba0-3edc-43d3-b51e-cdc7d509f37e)
![Screenshot_20240105-003125_Settings](https://github.com/SuperiorOS/android-issue/assets/155672212/d7d4bf9e-79c9-48f7-a956-02ca81fa73b6)
![Screenshot_20240105-003134_Settings](https://github.com/SuperiorOS/android-issue/assets/155672212/14689b79-dc4b-435a-aa9d-874279d0e85c)

**Security-** This section is lacking face unlock option. I don't know it was not added or it is a glitch.

**Navigation Bar-** There is no option in settings to hide it. 

**Auto/Adaptive Brightness** - Sometimes brightness drops to 1% just by moving phone a little bit even when I am in well lit area.

**Default apps**- You should add some more options there like "Default Video Player" Or "Music Player".

> **Apps-**

**Camera** - Man... In this update camera got F up. It's lacking in picture quality and can't balance light In normal condition. Every photo I click using this app is white no details at all. When switch to selfie camera the app closes. _Please fix this_.
1st photo is from pre installed camera without flash-
![IMG_20240105_010807](https://github.com/SuperiorOS/android-issue/assets/155672212/ca0657c0-e078-4ff2-b3a1-5fdb5389fc8d)
2nd photo is taken from gcam without flash-
![LMC_20240105_010824_lmc_8 4](https://github.com/SuperiorOS/android-issue/assets/155672212/2ec4f63c-82b8-410b-ae5b-47bac921f231)

**Gallery-** Needs to be optimised and add some options like MI Gallery had documents tab or screenshots. Like  this.

**Dialer-** The call recording option is not working at all. And I was not able to find `auto recording` option anywhere.

> _**Note:**_
I love this rom. Please fix these issues👃👃, it took a lot of time to write in mobile.

**Comment by Darkstar085** [comment]
Except camera other things are nlt relevant..

**Comment by Darkstar085** [comment]
Also u didn't provided any logs for the matter..

**Comment by Sayak46** [comment]
I don't know how to get logs so I searched Google and here it is. Don't know it will help or not. Sorry.
[logcat.txt](https://github.com/SuperiorOS/android-issue/files/13841551/logcat.txt)

**Comment by Sayak46** [comment]
I have uploaded a log file in comment section. Let me know it helps or not.
