### ISSUE TITLE
Alert Slider doesn't works .

### ISSUE THREAD

**Issue by marvinfischenich** [SuperiorOS/android-issue#29]
## Build date

```
SuperiorOS-Fourteen-avicii-GAPPS-RELEASE-20240118-0529
```

## Expected Behavior

```
When i move the volume slider to ring, vibrate or silent, the phone's mode should change accordingly
```

## Current Behavior

```
When i move the volume slider nothing happens, the ring-mode stays as is.
```

## Possible Solution

```
When the slider is moved, the phone's mode should change accordingly
```

## Logs link 

```
https://batbin.me/fc84f6d6db874f8fa691805b718ab4e7
```

## Steps to Reproduce

```
1. Move slider to ring / vibrate / silent
2. Check if phone's mode has changed
```

**Comment by Darkstar085** [comment]
Reboot and check..

**Comment by marvinfischenich** [comment]
I already rebooted a couple of times.
Did is once more now.
Nothing changed, alert slider still not working.

**Comment by Darkstar085** [comment]
Can u show me the about phone SS ..

**Comment by marvinfischenich** [comment]
is german fine for you?
if not i can change to english.

just removed some private info.

![Screenshot_20240205-130754_Einstellungen](https://github.com/SuperiorOS/android-issue/assets/107919586/3365abfb-a4fe-4b22-bc98-a32587a5e2e4)
![Screenshot_20240205-130751_Einstellungen(1)](https://github.com/SuperiorOS/android-issue/assets/107919586/b5556579-9109-463e-8e41-ad4885b25a3f)

**Comment by marvinfischenich** [comment]
this is solved with feb build
