### ISSUE TITLE
Permission controller keeps crashing

### ISSUE THREAD

**Issue by yesdopepe** [SuperiorOS/android-issue#4]
![Screenshot_20230224-114243](https://user-images.githubusercontent.com/87980431/221133818-9fb3856b-3526-403f-94d9-2a605c75c70f.png)

So I had this issue for a couple times, when I first booted up and when I install apps, here is the crash log:
https://bin.kv2.dev/~63f87674e599576ea02bc655

**Comment by Darkstar085** [comment]
Use proper report format..
