### ISSUE TITLE
I can't enable DSDS (option disappeared)

### ISSUE THREAD

**Issue by Rzqnoga** [SuperiorOS/android-issue#6]
## Build date

```
SuperiorOS-Thirteen-lancelot-GAPPS-RELEASE-20230211-0602
```

## Expected Behavior

```
It should enable 
```

## Current Behavior

```
When i disabled dsds option, phone info stopped responding and when i tried to reboot i went ito phone info, i found that dsds option disappeared 
```

## Possible Solution

```
Edit here
```

## Logs link 

```
Edit here
```

## Steps to Reproduce

```
1. In dial pad write *#*#4636#*#*  and go to phone information, disabled DSDS option then reboot the phone
```

**Comment by Darkstar085** [comment]
@01soni247

**Comment by 01soni247** [comment]
the smartphone is dual sim, better not turn it off

**Comment by 01soni247** [comment]
it will make your smartphone a single sim, better data format

**Comment by 01soni247** [comment]
> ## Build date
> ```
> SuperiorOS-Thirteen-lancelot-GAPPS-RELEASE-20230211-0602
> ```
> 
> ## Expected Behavior
> ```
> It should enable 
> ```
> 
> ## Current Behavior
> ```
> When i disabled dsds option, phone info stopped responding and when i tried to reboot i went ito phone info, i found that dsds option disappeared 
> ```
> 
> ## Possible Solution
> ```
> Edit here
> ```
> 
> ## Logs link
> ```
> Edit here
> ```
> 
> ## Steps to Reproduce
> ```
> 1. In dial pad write *#*#4636#*#*  and go to phone information, disabled DSDS option then reboot the phone
> ```

![Uploading Screenshot_20230308-222908.png…]()

**Comment by Rzqnoga** [comment]
I don't wonna to lose data, any solution?

**Comment by Joker-V2** [comment]
You are playing with unwanted stuffs !!!

**Comment by Rzqnoga** [comment]
> > I don't wonna to lose data, any solution?
> 
> https://www.google.com/url?sa=t&source=web&rct=j&url=https://forum.xda-developers.com/t/dsds-disabled-in-engineering-mode-4636-cant-enable-now-please-help.4139247/&ved=2ahUKEwjzx_im18z9AhVHzzgGHa3ACAw4ChAWegQICBAB&usg=AOvVaw2lSTJiAliUaJKV7ggCubjo

Someone said that he did factory reset but still the same problem

**Comment by 01soni247** [comment]
> > > I don't wonna to lose data, any solution?
> > 
> > 
> > https://www.google.com/url?sa=t&source=web&rct=j&url=https://forum.xda-developers.com/t/dsds-disabled-in-engineering-mode-4636-cant-enable-now-please-help.4139247/&ved=2ahUKEwjzx_im18z9AhVHzzgGHa3ACAw4ChAWegQICBAB&usg=AOvVaw2lSTJiAliUaJKV7ggCubjo
> 
> Someone said that he did factory reset but still the same problem

https://forum.xda-developers.com/t/guide-enable-dual-sim-dsds-on-your-t-mobile-8t-kb2007-with-lineage-aosp-rom.4262669/

**Comment by 01soni247** [comment]
> > > I don't wonna to lose data, any solution?
> > 
> > 
> > https://www.google.com/url?sa=t&source=web&rct=j&url=https://forum.xda-developers.com/t/dsds-disabled-in-engineering-mode-4636-cant-enable-now-please-help.4139247/&ved=2ahUKEwjzx_im18z9AhVHzzgGHa3ACAw4ChAWegQICBAB&usg=AOvVaw2lSTJiAliUaJKV7ggCubjo
> 
> Someone said that he did factory reset but still the same problem

Or Flash You Backup IMEI
