### ISSUE TITLE
Bluetooth icon not hidding in status bar

### ISSUE THREAD

**Issue by warlord00** [SuperiorOS/android-issue#7]
## Build date

```
SuperiorOS-Thirteen-raphael-RELEASE-20230308-1657
```

## Expected Behavior
 when i hide Bluetooth icon from status bar from superior lab settings icon of battery status of devices which connected to my device should hide with bluetooth icon 
```
Edit here
```

## Current Behavior
 bluetooth devices battery status not hiding after turning off from settings 
```
Edit here
```

## Possible Solution
in other roms there is a option for turning it's off you can bring that or just hide with bluetooth icon 
```
Edit here
```

## Logs link 
https://github.com/SuperiorOS/android-issue/files/10853746/2023-02-28-23-56-39.txt  
```
Edit here
```

## Steps to Reproduce

```
1.Go to settings 
2.open superior lab and click on status bar
3.hide Bluetooth icon 
4.connect bluetooth device like airbirds icon will show in status bar even after hiding from settings 
```

**Comment by Darkstar085** [comment]
Fixed with March update.. u have to hide the BT battery icon first then hide the BT icon..
